### ISSUE TITLE
Outlet interaction with Client for off-chain tokens

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/token-negotiator#175]
In the current flow Outlet sends all tokens to the Client (any third party website).
In this case I can see some security issue:

Example: some website embed Client and set passive negotiation, so when user visit this page then website can collect all user tokens without any notification.

I suggest to update flow and set passive/active in the Outlet only, so outlet page (owned by Token issuer) decide is it allowed to share tokens silently with other pages or have to ask use permission.

Its related to the Off-chain(attestation) tokens.

In this case token selector should be appeared on the Outlet iframe/tab

@nicktaras , @micwallace , did I miss something?

**Comment by nicktaras** [comment]
Hi Oleh, I can understand the confusion from changes since we were both fully working on the Library. A direction was taken to remove the UI check if the user was happy to enable the tokens to be read.

Let us discuss this at a product level. Ill check in with Basti who is planning the TN road map, ensuring this is added as a review item.

On 23 Apr 2022, at 3:43 am, oleggrib ***@***.***> wrote:

﻿

In the current flow Outlet sends all tokens to the Client (any third party website).
In this case I can see some security issue:

Example: some website embed Client and set passive negotiation, so when user visit this page then website can collect all user tokens without any notification.

I suggest to update flow and set passive/active in the Outlet only, so outlet page (owned by Token issuer) decide is it allowed to share tokens silently with other pages or have to ask use permission.

Its related to the Off-chain(attestation) tokens.

In this case token selector should be appeared on the Outlet iframe/tab

@nicktaras<https://github.com/nicktaras> , @micwallace<https://github.com/micwallace> , did I miss something?

**Comment by nicktaras** [comment]
Jira ticket added to address this TKN-163

**Comment by oleggrib** [comment]
Looks like this problem solved with whitelists, right @nicktaras ?
